version: '2'
services:
  redis:
    image: redis:3.2.6
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./redis:/data
    networks:
      - redisnet
networks:
  redisnet:
    driver: bridge

