version: '2'
services:
  redis:
    image: redis:3.2.6
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./redis:/data
    networks:
      - bnet

  mongodb:
    image: mongo:3.2.17
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./mongodb:/data/db
    networks:
      - bnet

networks:
  bnet:
    driver: bridge

