version: '2'
services:
  mongodb:
    image: mongo:3.2.17
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./mongodb:/data/db
    networks:
      - mongonet

networks:
  mongonet:
    driver: bridge

