version: '2'
services:
  mongodb:
    image: mongo:4.0
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./mongodb:/data/db
    networks:
      - mongodb_net

networks:
  mongodb_net:
    driver: bridge

