#!/bin/bash

##
if [ $1 = "help" ] || [ -z "$2" ]; then
  echo "Usage: service start [services]"
  echo "You can use labor, cache etc. to check all servers in that group"
  echo ""
  echo "services:"
  echo "elasticsearch -- elasticsearch available on 9200"
  echo "memcached -- memcached daemon available on 11211"
  echo "redis -- redis available on 6379"
  echo "mongodb -- mongodb available on 27017"
fi

### TODO: Pass version as variable redis -v 1.3.5
### https://docs.docker.com/compose/environment-variables/

# Select if we should start or stop the service
case $1 in
  start)
  CMD="up -d"
  ;;
  stop)
  CMD="down"
  ;;
esac

for i in "$@"; do
  echo $1
  case $i in
    memcached)
      docker-compose --file ./docker-compose-memcached.yml $CMD
      shift
    ;;
    redis)
      docker-compose --file ./docker-compose-redis.yml $CMD
      shift
    ;;
    mongodb)
      docker-compose --file ./docker-compose-mongodb.yml $CMD
      shift
    ;;
    solr)
      docker-compose --file ./solr/docker-compose.yml $CMD
      shift
    ;;
    elasticsearch)
      docker-compose --file ./elasticsearch/docker-compose.yml $CMD
      shift
    ;;
    *)
      shift
    ;;
  esac
done