#!/bin/bash

##
if [ -z "$2" ] || [ $1 = "--help" ] || [ $1 = "-h" ]; then
  echo
  echo "Usage: service start [services]"
  echo "Usage: service stop [services]"
  echo "You can start/stop multiple services with one call by separating them with space."
  echo ""
  echo "services:"
  echo "elasticsearch -- elasticsearch available on 9200"
  echo "memcached -- memcached daemon available on 11211"
  echo "mongodb -- mongodb available on 27017"
  echo "redis -- redis available on 6379"
  echo "solr -- solr available on 8983"
  echo
  exit 0
fi

### TODO: Pass version as variable redis -v 1.3.5
### https://docs.docker.com/compose/environment-variables/

# Select if we should start or stop the service
case $1 in
  start)
  CMD="up -d"
  ;;
  stop)
  CMD="down"
  ;;
esac

PREFIX="COMPOSE_IGNORE_ORPHANS=true"

printf "$1: "
for i in "$@"; do
  case $i in
    start) ;; stop)
      shift
      ;;
    memcached)
      docker-compose --file ./docker-compose-memcached.yml $CMD
      shift
    ;;
    redis)
      docker-compose --file ./docker-compose-redis.yml $CMD
      shift
    ;;
    mongodb)
      docker-compose --file ./docker-compose-mongodb.yml $CMD
      shift
    ;;
    solr)
      docker-compose --file ./solr/docker-compose.yml $CMD
      shift
    ;;
    elasticsearch)
      docker-compose --file ./elasticsearch/docker-compose.yml $CMD
      shift
    ;;
    *)
      echo "Unknown service $i"
      shift
    ;;
  esac
done