version: '2'
services:
  solr:
    build: .
    ports:
      - 127.0.0.1:8983:8983
    volumes:
      - ../../var/solr/data:/opt/solr/data
      - ../../var/solr/config:/opt/solr/server/solr/configsets
    networks:
      - solr_net

networks:
  solr_net:
    driver: bridge

