# More info:
# https://www.dragonflydb.io/docs/getting-started/docker-compose
version: '2'
services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ../var/dragonfly:/data
    networks:
      - dragonfly_net
networks:
  dragonfly_net:
    driver: bridge


