# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=******
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=test_db
    volumes:
      - ../var/postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

    networks:
      - postgres_net

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

networks:
  postgres_net:
    driver: bridge