version: '2'
services:
  mysql:
    image: mysql:8
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ../var/mysql:/var/lib/mysql
    networks:
      - mysql_net
    environment:
      - "MYSQL_ROOT_PASSWORD=pwd4life"
networks:
  mysql_net:
    driver: bridge

