version: '2'
services:
  redis:
    image: redis:7.0.8
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ../var/redis:/data
    networks:
      - redis_net
networks:
  redis_net:
    driver: bridge

