version: '2'
services:
  solr:
    build: .
    ports:
      - 8983:8983
    volumes:
      - ./data:/opt/solr/data
      - ./config:/opt/solr/conf
    networks:
      - bnet

networks:
  bnet:
    driver: bridge

